version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - gosec
    - grouper
    - loggercheck
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    gomoddirectives:
      replace-allow-list:
        - github.com/gin-gonic/gin
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoglobals
          - goconst
          - gocyclo
        path: _test\.go$
    paths:
      - .*\.capnp\.go$
      - .*_configulator\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - .*\.capnp\.go$
      - .*_configulator\.go$
      - third_party$
      - builtin$
      - examples$
