// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type tracingShadow struct {
	Enabled      *bool   `json:"enabled"       toml:"enabled"       yaml:"enabled"`
	OTLPEndpoint *string `json:"otlp_endpoint" toml:"otlp_endpoint" yaml:"otlp_endpoint"`
}

type pProfShadow struct {
	Enabled *bool `json:"enabled" toml:"enabled" yaml:"enabled"`
}

type metricsShadow struct {
	IPV4Host *string `json:"ipv4_host" toml:"ipv4_host" yaml:"ipv4_host"`
	IPV6Host *string `json:"ipv6_host" toml:"ipv6_host" yaml:"ipv6_host"`
	Port     *uint16 `json:"port"      toml:"port"      yaml:"port"`
	Enabled  *bool   `json:"enabled"   toml:"enabled"   yaml:"enabled"`
}

type hTTPShadow struct {
	IPV4Host       *string        `json:"ipv4_host"       toml:"ipv4_host"       yaml:"ipv4_host"`
	IPV6Host       *string        `json:"ipv6_host"       toml:"ipv6_host"       yaml:"ipv6_host"`
	Port           *uint16        `json:"port"            toml:"port"            yaml:"port"`
	Tracing        *tracingShadow `json:"tracing"         toml:"tracing"         yaml:"tracing"`
	BackendURL     *string        `json:"backend_url"     toml:"backend_url"     yaml:"backend_url"`
	PProf          *pProfShadow   `json:"pprof"           toml:"pprof"           yaml:"pprof"`
	TrustedProxies *[]string      `json:"trusted_proxies" toml:"trusted_proxies" yaml:"trusted_proxies"`
	Metrics        *metricsShadow `json:"metrics"         toml:"metrics"         yaml:"metrics"`
	CORSHosts      *[]string      `json:"cors_hosts"      toml:"cors_hosts"      yaml:"cors_hosts"`
}

type databaseShadow struct {
	Driver          *string `json:"driver"           toml:"driver"           yaml:"driver"`
	Database        *string `json:"database"         toml:"database"         yaml:"database"`
	Username        *string `json:"username"         toml:"username"         yaml:"username"`
	Password        *string `json:"password"         toml:"password"         yaml:"password"`
	Host            *string `json:"host"             toml:"host"             yaml:"host"`
	Port            *uint16 `json:"port"             toml:"port"             yaml:"port"`
	ExtraParameters *string `json:"extra_parameters" toml:"extra_parameters" yaml:"extra_parameters"`
}

type filesystemOptionsShadow struct {
	Directory *string `json:"directory" toml:"directory" yaml:"directory"`
}

type s3OptionsShadow struct {
	Region   *string `json:"region"   toml:"region"   yaml:"region"`
	Bucket   *string `json:"bucket"   toml:"bucket"   yaml:"bucket"`
	Endpoint *string `json:"endpoint" toml:"endpoint" yaml:"endpoint"`
}

type uploadsShadow struct {
	Driver            *string                  `json:"driver"             toml:"driver"             yaml:"driver"`
	FilesystemOptions *filesystemOptionsShadow `json:"filesystem_options" toml:"filesystem_options" yaml:"filesystem_options"`
	S3Options         *s3OptionsShadow         `json:"s3_options"         toml:"s3_options"         yaml:"s3_options"`
}

type persistenceShadow struct {
	Database *databaseShadow `json:"database" toml:"database" yaml:"database"`
	Uploads  *uploadsShadow  `json:"uploads"  toml:"uploads"  yaml:"uploads"`
}

type registrationShadow struct {
	Enabled *bool `json:"enabled" toml:"enabled" yaml:"enabled"`
}

type googleShadow struct {
	Enabled      *bool   `json:"enabled"       toml:"enabled"       yaml:"enabled"`
	ClientID     *string `json:"client_id"     toml:"client_id"     yaml:"client_id"`
	ClientSecret *string `json:"client_secret" toml:"client_secret" yaml:"client_secret"`
}

type gitHubShadow struct {
	Enabled      *bool   `json:"enabled"       toml:"enabled"       yaml:"enabled"`
	ClientID     *string `json:"client_id"     toml:"client_id"     yaml:"client_id"`
	ClientSecret *string `json:"client_secret" toml:"client_secret" yaml:"client_secret"`
}

type customShadow struct {
	Enabled      *bool   `json:"enabled"       toml:"enabled"       yaml:"enabled"`
	ClientID     *string `json:"client_id"     toml:"client_id"     yaml:"client_id"`
	ClientSecret *string `json:"client_secret" toml:"client_secret" yaml:"client_secret"`
	TokenURL     *string `json:"token_url"     toml:"token_url"     yaml:"token_url"`
	UserURL      *string `json:"user_url"      toml:"user_url"      yaml:"user_url"`
}

type authShadow struct {
	Google *googleShadow `json:"google" toml:"google" yaml:"google"`
	GitHub *gitHubShadow `json:"github" toml:"github" yaml:"github"`
	Custom *customShadow `json:"custom" toml:"custom" yaml:"custom"`
}

type jWTShadow struct {
	Secret *string `json:"secret" toml:"secret" yaml:"secret"`
}

type mapboxShadow struct {
	SecretToken *string `json:"secret_token" toml:"secret_token" yaml:"secret_token"`
	PublicToken *string `json:"public_token" toml:"public_token" yaml:"public_token"`
}

type nATSShadow struct {
	Enabled *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	URL     *string `json:"url"     toml:"url"     yaml:"url"`
	Token   *string `json:"token"   toml:"token"   yaml:"token"`
}

type configShadow struct {
	HTTP               *hTTPShadow         `json:"http"                 toml:"http"                 yaml:"http"`
	Persistence        *persistenceShadow  `json:"persistence"          toml:"persistence"          yaml:"persistence"`
	Registration       *registrationShadow `json:"registration"         toml:"registration"         yaml:"registration"`
	Auth               *authShadow         `json:"auth"                 toml:"auth"                 yaml:"auth"`
	JWT                *jWTShadow          `json:"jwt"                  toml:"jwt"                  yaml:"jwt"`
	Mapbox             *mapboxShadow       `json:"mapbox"               toml:"mapbox"               yaml:"mapbox"`
	NATS               *nATSShadow         `json:"nats"                 toml:"nats"                 yaml:"nats"`
	ParallelLogParsers *uint               `json:"parallel_log_parsers" toml:"parallel_log_parsers" yaml:"parallel_log_parsers"`
	LogLevel           *string             `json:"log_level"            toml:"log_level"            yaml:"log_level"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
		Required:      []string{"http.backend_url", "jwt.secret", "mapbox.secret_token", "mapbox.public_token"},
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.HTTP.IPV4Host = "0.0.0.0"
	set("http.ipv4_host", configulator.LayerDefault, "default tag")
	cfg.HTTP.IPV6Host = "::"
	set("http.ipv6_host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = uint16(8080)
	set("http.port", configulator.LayerDefault, "default tag")
	cfg.HTTP.Metrics.IPV4Host = "127.0.0.1"
	set("http.metrics.ipv4_host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Metrics.IPV6Host = "::1"
	set("http.metrics.ipv6_host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Metrics.Port = uint16(8081)
	set("http.metrics.port", configulator.LayerDefault, "default tag")
	cfg.Persistence.Database.Driver = DatabaseDriver("sqlite")
	set("persistence.database.driver", configulator.LayerDefault, "default tag")
	cfg.Persistence.Database.Database = "rtz.db"
	set("persistence.database.database", configulator.LayerDefault, "default tag")
	cfg.Persistence.Uploads.Driver = UploadsDriver("filesystem")
	set("persistence.uploads.driver", configulator.LayerDefault, "default tag")
	cfg.Persistence.Uploads.FilesystemOptions.Directory = "uploads/"
	set("persistence.uploads.filesystem_options.directory", configulator.LayerDefault, "default tag")
	cfg.ParallelLogParsers = uint(4)
	set("parallel_log_parsers", configulator.LayerDefault, "default tag")
	cfg.LogLevel = LogLevel("info")
	set("log_level", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.HTTP != nil {
		if s.HTTP.IPV4Host != nil {
			cfg.HTTP.IPV4Host = *s.HTTP.IPV4Host
			set("http.ipv4_host", configulator.LayerFile, file)
		}
		if s.HTTP.IPV6Host != nil {
			cfg.HTTP.IPV6Host = *s.HTTP.IPV6Host
			set("http.ipv6_host", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
		if s.HTTP.Tracing != nil {
			if s.HTTP.Tracing.Enabled != nil {
				cfg.HTTP.Tracing.Enabled = *s.HTTP.Tracing.Enabled
				set("http.tracing.enabled", configulator.LayerFile, file)
			}
			if s.HTTP.Tracing.OTLPEndpoint != nil {
				cfg.HTTP.Tracing.OTLPEndpoint = *s.HTTP.Tracing.OTLPEndpoint
				set("http.tracing.otlp_endpoint", configulator.LayerFile, file)
			}
		}
		if s.HTTP.BackendURL != nil {
			cfg.HTTP.BackendURL = *s.HTTP.BackendURL
			set("http.backend_url", configulator.LayerFile, file)
		}
		if s.HTTP.PProf != nil {
			if s.HTTP.PProf.Enabled != nil {
				cfg.HTTP.PProf.Enabled = *s.HTTP.PProf.Enabled
				set("http.pprof.enabled", configulator.LayerFile, file)
			}
		}
		if s.HTTP.TrustedProxies != nil {
			cfg.HTTP.TrustedProxies = *s.HTTP.TrustedProxies
			set("http.trusted_proxies", configulator.LayerFile, file)
		}
		if s.HTTP.Metrics != nil {
			if s.HTTP.Metrics.IPV4Host != nil {
				cfg.HTTP.Metrics.IPV4Host = *s.HTTP.Metrics.IPV4Host
				set("http.metrics.ipv4_host", configulator.LayerFile, file)
			}
			if s.HTTP.Metrics.IPV6Host != nil {
				cfg.HTTP.Metrics.IPV6Host = *s.HTTP.Metrics.IPV6Host
				set("http.metrics.ipv6_host", configulator.LayerFile, file)
			}
			if s.HTTP.Metrics.Port != nil {
				cfg.HTTP.Metrics.Port = *s.HTTP.Metrics.Port
				set("http.metrics.port", configulator.LayerFile, file)
			}
			if s.HTTP.Metrics.Enabled != nil {
				cfg.HTTP.Metrics.Enabled = *s.HTTP.Metrics.Enabled
				set("http.metrics.enabled", configulator.LayerFile, file)
			}
		}
		if s.HTTP.CORSHosts != nil {
			cfg.HTTP.CORSHosts = *s.HTTP.CORSHosts
			set("http.cors_hosts", configulator.LayerFile, file)
		}
	}
	if s.Persistence != nil {
		if s.Persistence.Database != nil {
			if s.Persistence.Database.Driver != nil {
				cfg.Persistence.Database.Driver = DatabaseDriver(*s.Persistence.Database.Driver)
				set("persistence.database.driver", configulator.LayerFile, file)
			}
			if s.Persistence.Database.Database != nil {
				cfg.Persistence.Database.Database = *s.Persistence.Database.Database
				set("persistence.database.database", configulator.LayerFile, file)
			}
			if s.Persistence.Database.Username != nil {
				cfg.Persistence.Database.Username = *s.Persistence.Database.Username
				set("persistence.database.username", configulator.LayerFile, file)
			}
			if s.Persistence.Database.Password != nil {
				cfg.Persistence.Database.Password = *s.Persistence.Database.Password
				set("persistence.database.password", configulator.LayerFile, file)
			}
			if s.Persistence.Database.Host != nil {
				cfg.Persistence.Database.Host = *s.Persistence.Database.Host
				set("persistence.database.host", configulator.LayerFile, file)
			}
			if s.Persistence.Database.Port != nil {
				cfg.Persistence.Database.Port = *s.Persistence.Database.Port
				set("persistence.database.port", configulator.LayerFile, file)
			}
			if s.Persistence.Database.ExtraParameters != nil {
				cfg.Persistence.Database.ExtraParameters = *s.Persistence.Database.ExtraParameters
				set("persistence.database.extra_parameters", configulator.LayerFile, file)
			}
		}
		if s.Persistence.Uploads != nil {
			if s.Persistence.Uploads.Driver != nil {
				cfg.Persistence.Uploads.Driver = UploadsDriver(*s.Persistence.Uploads.Driver)
				set("persistence.uploads.driver", configulator.LayerFile, file)
			}
			if s.Persistence.Uploads.FilesystemOptions != nil {
				if s.Persistence.Uploads.FilesystemOptions.Directory != nil {
					cfg.Persistence.Uploads.FilesystemOptions.Directory = *s.Persistence.Uploads.FilesystemOptions.Directory
					set("persistence.uploads.filesystem_options.directory", configulator.LayerFile, file)
				}
			}
			if s.Persistence.Uploads.S3Options != nil {
				if s.Persistence.Uploads.S3Options.Region != nil {
					cfg.Persistence.Uploads.S3Options.Region = *s.Persistence.Uploads.S3Options.Region
					set("persistence.uploads.s3_options.region", configulator.LayerFile, file)
				}
				if s.Persistence.Uploads.S3Options.Bucket != nil {
					cfg.Persistence.Uploads.S3Options.Bucket = *s.Persistence.Uploads.S3Options.Bucket
					set("persistence.uploads.s3_options.bucket", configulator.LayerFile, file)
				}
				if s.Persistence.Uploads.S3Options.Endpoint != nil {
					cfg.Persistence.Uploads.S3Options.Endpoint = *s.Persistence.Uploads.S3Options.Endpoint
					set("persistence.uploads.s3_options.endpoint", configulator.LayerFile, file)
				}
			}
		}
	}
	if s.Registration != nil {
		if s.Registration.Enabled != nil {
			cfg.Registration.Enabled = *s.Registration.Enabled
			set("registration.enabled", configulator.LayerFile, file)
		}
	}
	if s.Auth != nil {
		if s.Auth.Google != nil {
			if s.Auth.Google.Enabled != nil {
				cfg.Auth.Google.Enabled = *s.Auth.Google.Enabled
				set("auth.google.enabled", configulator.LayerFile, file)
			}
			if s.Auth.Google.ClientID != nil {
				cfg.Auth.Google.ClientID = *s.Auth.Google.ClientID
				set("auth.google.client_id", configulator.LayerFile, file)
			}
			if s.Auth.Google.ClientSecret != nil {
				cfg.Auth.Google.ClientSecret = *s.Auth.Google.ClientSecret
				set("auth.google.client_secret", configulator.LayerFile, file)
			}
		}
		if s.Auth.GitHub != nil {
			if s.Auth.GitHub.Enabled != nil {
				cfg.Auth.GitHub.Enabled = *s.Auth.GitHub.Enabled
				set("auth.github.enabled", configulator.LayerFile, file)
			}
			if s.Auth.GitHub.ClientID != nil {
				cfg.Auth.GitHub.ClientID = *s.Auth.GitHub.ClientID
				set("auth.github.client_id", configulator.LayerFile, file)
			}
			if s.Auth.GitHub.ClientSecret != nil {
				cfg.Auth.GitHub.ClientSecret = *s.Auth.GitHub.ClientSecret
				set("auth.github.client_secret", configulator.LayerFile, file)
			}
		}
		if s.Auth.Custom != nil {
			if s.Auth.Custom.Enabled != nil {
				cfg.Auth.Custom.Enabled = *s.Auth.Custom.Enabled
				set("auth.custom.enabled", configulator.LayerFile, file)
			}
			if s.Auth.Custom.ClientID != nil {
				cfg.Auth.Custom.ClientID = *s.Auth.Custom.ClientID
				set("auth.custom.client_id", configulator.LayerFile, file)
			}
			if s.Auth.Custom.ClientSecret != nil {
				cfg.Auth.Custom.ClientSecret = *s.Auth.Custom.ClientSecret
				set("auth.custom.client_secret", configulator.LayerFile, file)
			}
			if s.Auth.Custom.TokenURL != nil {
				cfg.Auth.Custom.TokenURL = *s.Auth.Custom.TokenURL
				set("auth.custom.token_url", configulator.LayerFile, file)
			}
			if s.Auth.Custom.UserURL != nil {
				cfg.Auth.Custom.UserURL = *s.Auth.Custom.UserURL
				set("auth.custom.user_url", configulator.LayerFile, file)
			}
		}
	}
	if s.JWT != nil {
		if s.JWT.Secret != nil {
			cfg.JWT.Secret = *s.JWT.Secret
			set("jwt.secret", configulator.LayerFile, file)
		}
	}
	if s.Mapbox != nil {
		if s.Mapbox.SecretToken != nil {
			cfg.Mapbox.SecretToken = *s.Mapbox.SecretToken
			set("mapbox.secret_token", configulator.LayerFile, file)
		}
		if s.Mapbox.PublicToken != nil {
			cfg.Mapbox.PublicToken = *s.Mapbox.PublicToken
			set("mapbox.public_token", configulator.LayerFile, file)
		}
	}
	if s.NATS != nil {
		if s.NATS.Enabled != nil {
			cfg.NATS.Enabled = *s.NATS.Enabled
			set("nats.enabled", configulator.LayerFile, file)
		}
		if s.NATS.URL != nil {
			cfg.NATS.URL = *s.NATS.URL
			set("nats.url", configulator.LayerFile, file)
		}
		if s.NATS.Token != nil {
			cfg.NATS.Token = *s.NATS.Token
			set("nats.token", configulator.LayerFile, file)
		}
	}
	if s.ParallelLogParsers != nil {
		cfg.ParallelLogParsers = *s.ParallelLogParsers
		set("parallel_log_parsers", configulator.LayerFile, file)
	}
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log_level", configulator.LayerFile, file)
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "ipv4_host"); ok {
		cfg.HTTP.IPV4Host = v
		set("http.ipv4_host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "ipv6_host"); ok {
		cfg.HTTP.IPV6Host = v
		set("http.ipv6_host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Port = uint16(p)
		set("http.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "tracing", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.tracing.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Tracing.Enabled = p
		set("http.tracing.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "tracing", "otlp_endpoint"); ok {
		cfg.HTTP.Tracing.OTLPEndpoint = v
		set("http.tracing.otlp_endpoint", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "backend_url"); ok {
		cfg.HTTP.BackendURL = v
		set("http.backend_url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "pprof", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.pprof.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.PProf.Enabled = p
		set("http.pprof.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "trusted_proxies"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.HTTP.TrustedProxies = lst
		set("http.trusted_proxies", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "metrics", "ipv4_host"); ok {
		cfg.HTTP.Metrics.IPV4Host = v
		set("http.metrics.ipv4_host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "metrics", "ipv6_host"); ok {
		cfg.HTTP.Metrics.IPV6Host = v
		set("http.metrics.ipv6_host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "metrics", "port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Metrics.Port = uint16(p)
		set("http.metrics.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "metrics", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Metrics.Enabled = p
		set("http.metrics.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "cors_hosts"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.HTTP.CORSHosts = lst
		set("http.cors_hosts", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "persistence", "database", "driver"); ok {
		cfg.Persistence.Database.Driver = DatabaseDriver(v)
		set("persistence.database.driver", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "persistence", "database", "database"); ok {
		cfg.Persistence.Database.Database = v
		set("persistence.database.database", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "persistence", "database", "username"); ok {
		cfg.Persistence.Database.Username = v
		set("persistence.database.username", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "persistence", "database", "password"); ok {
		cfg.Persistence.Database.Password = v
		set("persistence.database.password", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "persistence", "database", "host"); ok {
		cfg.Persistence.Database.Host = v
		set("persistence.database.host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "persistence", "database", "port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.database.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Persistence.Database.Port = uint16(p)
		set("persistence.database.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "persistence", "database", "extra_parameters"); ok {
		cfg.Persistence.Database.ExtraParameters = v
		set("persistence.database.extra_parameters", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "persistence", "uploads", "driver"); ok {
		cfg.Persistence.Uploads.Driver = UploadsDriver(v)
		set("persistence.uploads.driver", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "persistence", "uploads", "filesystem_options", "directory"); ok {
		cfg.Persistence.Uploads.FilesystemOptions.Directory = v
		set("persistence.uploads.filesystem_options.directory", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "persistence", "uploads", "s3_options", "region"); ok {
		cfg.Persistence.Uploads.S3Options.Region = v
		set("persistence.uploads.s3_options.region", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "persistence", "uploads", "s3_options", "bucket"); ok {
		cfg.Persistence.Uploads.S3Options.Bucket = v
		set("persistence.uploads.s3_options.bucket", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "persistence", "uploads", "s3_options", "endpoint"); ok {
		cfg.Persistence.Uploads.S3Options.Endpoint = v
		set("persistence.uploads.s3_options.endpoint", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "registration", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "registration.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.Registration.Enabled = p
		set("registration.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "google", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.google.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.Auth.Google.Enabled = p
		set("auth.google.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "google", "client_id"); ok {
		cfg.Auth.Google.ClientID = v
		set("auth.google.client_id", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "google", "client_secret"); ok {
		cfg.Auth.Google.ClientSecret = v
		set("auth.google.client_secret", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "github", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.github.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.Auth.GitHub.Enabled = p
		set("auth.github.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "github", "client_id"); ok {
		cfg.Auth.GitHub.ClientID = v
		set("auth.github.client_id", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "github", "client_secret"); ok {
		cfg.Auth.GitHub.ClientSecret = v
		set("auth.github.client_secret", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "custom", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.custom.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.Auth.Custom.Enabled = p
		set("auth.custom.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "custom", "client_id"); ok {
		cfg.Auth.Custom.ClientID = v
		set("auth.custom.client_id", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "custom", "client_secret"); ok {
		cfg.Auth.Custom.ClientSecret = v
		set("auth.custom.client_secret", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "custom", "token_url"); ok {
		cfg.Auth.Custom.TokenURL = v
		set("auth.custom.token_url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "custom", "user_url"); ok {
		cfg.Auth.Custom.UserURL = v
		set("auth.custom.user_url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "jwt", "secret"); ok {
		cfg.JWT.Secret = v
		set("jwt.secret", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mapbox", "secret_token"); ok {
		cfg.Mapbox.SecretToken = v
		set("mapbox.secret_token", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mapbox", "public_token"); ok {
		cfg.Mapbox.PublicToken = v
		set("mapbox.public_token", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "nats", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "nats.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.NATS.Enabled = p
		set("nats.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "nats", "url"); ok {
		cfg.NATS.URL = v
		set("nats.url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "nats", "token"); ok {
		cfg.NATS.Token = v
		set("nats.token", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "parallel_log_parsers"); ok {
		p, err := strconv.ParseUint(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "parallel_log_parsers",
				Source: n,
				Value:  v,
			}
		}
		cfg.ParallelLogParsers = uint(p)
		set("parallel_log_parsers", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "log_level"); ok {
		cfg.LogLevel = LogLevel(v)
		set("log_level", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"http" + o.Separator + "ipv4_host",
		"http" + o.Separator + "ipv6_host",
		"http" + o.Separator + "port",
		"http" + o.Separator + "tracing" + o.Separator + "enabled",
		"http" + o.Separator + "tracing" + o.Separator + "otlp_endpoint",
		"http" + o.Separator + "backend_url",
		"http" + o.Separator + "pprof" + o.Separator + "enabled",
		"http" + o.Separator + "trusted_proxies",
		"http" + o.Separator + "metrics" + o.Separator + "ipv4_host",
		"http" + o.Separator + "metrics" + o.Separator + "ipv6_host",
		"http" + o.Separator + "metrics" + o.Separator + "port",
		"http" + o.Separator + "metrics" + o.Separator + "enabled",
		"http" + o.Separator + "cors_hosts",
		"persistence" + o.Separator + "database" + o.Separator + "driver",
		"persistence" + o.Separator + "database" + o.Separator + "database",
		"persistence" + o.Separator + "database" + o.Separator + "username",
		"persistence" + o.Separator + "database" + o.Separator + "password",
		"persistence" + o.Separator + "database" + o.Separator + "host",
		"persistence" + o.Separator + "database" + o.Separator + "port",
		"persistence" + o.Separator + "database" + o.Separator + "extra_parameters",
		"persistence" + o.Separator + "uploads" + o.Separator + "driver",
		"persistence" + o.Separator + "uploads" + o.Separator + "filesystem_options" + o.Separator + "directory",
		"persistence" + o.Separator + "uploads" + o.Separator + "s3_options" + o.Separator + "region",
		"persistence" + o.Separator + "uploads" + o.Separator + "s3_options" + o.Separator + "bucket",
		"persistence" + o.Separator + "uploads" + o.Separator + "s3_options" + o.Separator + "endpoint",
		"registration" + o.Separator + "enabled",
		"auth" + o.Separator + "google" + o.Separator + "enabled",
		"auth" + o.Separator + "google" + o.Separator + "client_id",
		"auth" + o.Separator + "google" + o.Separator + "client_secret",
		"auth" + o.Separator + "github" + o.Separator + "enabled",
		"auth" + o.Separator + "github" + o.Separator + "client_id",
		"auth" + o.Separator + "github" + o.Separator + "client_secret",
		"auth" + o.Separator + "custom" + o.Separator + "enabled",
		"auth" + o.Separator + "custom" + o.Separator + "client_id",
		"auth" + o.Separator + "custom" + o.Separator + "client_secret",
		"auth" + o.Separator + "custom" + o.Separator + "token_url",
		"auth" + o.Separator + "custom" + o.Separator + "user_url",
		"jwt" + o.Separator + "secret",
		"mapbox" + o.Separator + "secret_token",
		"mapbox" + o.Separator + "public_token",
		"nats" + o.Separator + "enabled",
		"nats" + o.Separator + "url",
		"nats" + o.Separator + "token",
		"parallel_log_parsers",
		"log_level",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "0.0.0.0", "HTTP server IPv4 host")
	fs.String(names[1], "::", "HTTP server IPv6 host")
	fs.Uint16(names[2], 8080, "HTTP server port, shared by IPv4 and IPv6")
	fs.Bool(names[3], false, "Enable OpenTelemetry tracing")
	fs.String(names[4], "", "OpenTelemetry collector endpoint, required when tracing is enabled")
	fs.String(names[5], "", "Public URL of this server")
	fs.Bool(names[6], false, "Enable pprof")
	fs.StringSlice(names[7], nil, "IP addresses or CIDR ranges of reverse proxies trusted to set X-Forwarded-For")
	fs.String(names[8], "127.0.0.1", "Prometheus metrics server IPv4 host")
	fs.String(names[9], "::1", "Prometheus metrics server IPv6 host")
	fs.Uint16(names[10], 8081, "Prometheus metrics server port, shared by IPv4 and IPv6")
	fs.Bool(names[11], false, "Enable the Prometheus metrics server")
	fs.StringSlice(names[12], nil, "Hosts allowed by CORS")
	fs.String(names[13], "sqlite", "Database driver, one of: sqlite, mysql, postgres")
	fs.String(names[14], "rtz.db", "Path to the SQLite database file, or the database name for other drivers")
	fs.String(names[15], "", "Database username")
	fs.String(names[16], "", "Database password")
	fs.String(names[17], "", "Database host, required for mysql and postgres")
	fs.Uint16(names[18], 0, "Database port, 0 uses the driver's default")
	fs.String(names[19], "", "Extra parameters passed to the database driver")
	fs.String(names[20], "filesystem", "Storage driver for uploaded videos and driving logs, one of: filesystem, s3")
	fs.String(names[21], "uploads/", "Filesystem uploads directory, created if it does not exist")
	fs.String(names[22], "", "S3 region. Credentials come from the standard AWS environment variables, the AWS CLI config or an IAM role")
	fs.String(names[23], "", "S3 bucket")
	fs.String(names[24], "", "Custom S3 endpoint, which switches to path-style addressing")
	fs.Bool(names[25], false, "Enable user registration")
	fs.Bool(names[26], false, "Enable Google OAuth")
	fs.String(names[27], "", "Google OAuth client ID")
	fs.String(names[28], "", "Google OAuth client secret")
	fs.Bool(names[29], false, "Enable GitHub OAuth")
	fs.String(names[30], "", "GitHub OAuth client ID")
	fs.String(names[31], "", "GitHub OAuth client secret")
	fs.Bool(names[32], false, "Enable custom OAuth")
	fs.String(names[33], "", "Custom OAuth client ID")
	fs.String(names[34], "", "Custom OAuth client secret")
	fs.String(names[35], "", "Custom OAuth token URL")
	fs.String(names[36], "", "Custom OAuth user URL")
	fs.String(names[37], "", "JWT signing secret")
	fs.String(names[38], "", "Mapbox secret token")
	fs.String(names[39], "", "Mapbox public token")
	fs.Bool(names[40], false, "Enable NATS. Required when running more than one instance, such as blue/green deployments, so websockets reach the instance the device is connected to")
	fs.String(names[41], "", "NATS URL")
	fs.String(names[42], "", "NATS token")
	fs.Var(impl.NewUint(4), names[43], "Number of parallel log parsers")
	fs.String(names[44], "info", "Log level, one of: debug, info, warn, error")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "http" + o.Separator + "ipv4_host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.ipv4_host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.IPV4Host = v
		set("http.ipv4_host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "ipv6_host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.ipv6_host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.IPV6Host = v
		set("http.ipv6_host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "tracing" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.tracing.enabled",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Tracing.Enabled = v
		set("http.tracing.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "tracing" + o.Separator + "otlp_endpoint"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.tracing.otlp_endpoint",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Tracing.OTLPEndpoint = v
		set("http.tracing.otlp_endpoint", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "backend_url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.backend_url",
				Source: "--" + n,
			}
		}
		cfg.HTTP.BackendURL = v
		set("http.backend_url", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "pprof" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.pprof.enabled",
				Source: "--" + n,
			}
		}
		cfg.HTTP.PProf.Enabled = v
		set("http.pprof.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "trusted_proxies"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.trusted_proxies",
				Source: "--" + n,
			}
		}
		cfg.HTTP.TrustedProxies = v
		set("http.trusted_proxies", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "metrics" + o.Separator + "ipv4_host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.ipv4_host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Metrics.IPV4Host = v
		set("http.metrics.ipv4_host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "metrics" + o.Separator + "ipv6_host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.ipv6_host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Metrics.IPV6Host = v
		set("http.metrics.ipv6_host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "metrics" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Metrics.Port = v
		set("http.metrics.port", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "metrics" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.enabled",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Metrics.Enabled = v
		set("http.metrics.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "cors_hosts"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors_hosts",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORSHosts = v
		set("http.cors_hosts", configulator.LayerCLI, "--"+n)
	}
	if n := "persistence" + o.Separator + "database" + o.Separator + "driver"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.database.driver",
				Source: "--" + n,
			}
		}
		cfg.Persistence.Database.Driver = DatabaseDriver(v)
		set("persistence.database.driver", configulator.LayerCLI, "--"+n)
	}
	if n := "persistence" + o.Separator + "database" + o.Separator + "database"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.database.database",
				Source: "--" + n,
			}
		}
		cfg.Persistence.Database.Database = v
		set("persistence.database.database", configulator.LayerCLI, "--"+n)
	}
	if n := "persistence" + o.Separator + "database" + o.Separator + "username"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.database.username",
				Source: "--" + n,
			}
		}
		cfg.Persistence.Database.Username = v
		set("persistence.database.username", configulator.LayerCLI, "--"+n)
	}
	if n := "persistence" + o.Separator + "database" + o.Separator + "password"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.database.password",
				Source: "--" + n,
			}
		}
		cfg.Persistence.Database.Password = v
		set("persistence.database.password", configulator.LayerCLI, "--"+n)
	}
	if n := "persistence" + o.Separator + "database" + o.Separator + "host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.database.host",
				Source: "--" + n,
			}
		}
		cfg.Persistence.Database.Host = v
		set("persistence.database.host", configulator.LayerCLI, "--"+n)
	}
	if n := "persistence" + o.Separator + "database" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.database.port",
				Source: "--" + n,
			}
		}
		cfg.Persistence.Database.Port = v
		set("persistence.database.port", configulator.LayerCLI, "--"+n)
	}
	if n := "persistence" + o.Separator + "database" + o.Separator + "extra_parameters"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.database.extra_parameters",
				Source: "--" + n,
			}
		}
		cfg.Persistence.Database.ExtraParameters = v
		set("persistence.database.extra_parameters", configulator.LayerCLI, "--"+n)
	}
	if n := "persistence" + o.Separator + "uploads" + o.Separator + "driver"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.uploads.driver",
				Source: "--" + n,
			}
		}
		cfg.Persistence.Uploads.Driver = UploadsDriver(v)
		set("persistence.uploads.driver", configulator.LayerCLI, "--"+n)
	}
	if n := "persistence" + o.Separator + "uploads" + o.Separator + "filesystem_options" + o.Separator + "directory"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.uploads.filesystem_options.directory",
				Source: "--" + n,
			}
		}
		cfg.Persistence.Uploads.FilesystemOptions.Directory = v
		set("persistence.uploads.filesystem_options.directory", configulator.LayerCLI, "--"+n)
	}
	if n := "persistence" + o.Separator + "uploads" + o.Separator + "s3_options" + o.Separator + "region"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.uploads.s3_options.region",
				Source: "--" + n,
			}
		}
		cfg.Persistence.Uploads.S3Options.Region = v
		set("persistence.uploads.s3_options.region", configulator.LayerCLI, "--"+n)
	}
	if n := "persistence" + o.Separator + "uploads" + o.Separator + "s3_options" + o.Separator + "bucket"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.uploads.s3_options.bucket",
				Source: "--" + n,
			}
		}
		cfg.Persistence.Uploads.S3Options.Bucket = v
		set("persistence.uploads.s3_options.bucket", configulator.LayerCLI, "--"+n)
	}
	if n := "persistence" + o.Separator + "uploads" + o.Separator + "s3_options" + o.Separator + "endpoint"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "persistence.uploads.s3_options.endpoint",
				Source: "--" + n,
			}
		}
		cfg.Persistence.Uploads.S3Options.Endpoint = v
		set("persistence.uploads.s3_options.endpoint", configulator.LayerCLI, "--"+n)
	}
	if n := "registration" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "registration.enabled",
				Source: "--" + n,
			}
		}
		cfg.Registration.Enabled = v
		set("registration.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "google" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.google.enabled",
				Source: "--" + n,
			}
		}
		cfg.Auth.Google.Enabled = v
		set("auth.google.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "google" + o.Separator + "client_id"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.google.client_id",
				Source: "--" + n,
			}
		}
		cfg.Auth.Google.ClientID = v
		set("auth.google.client_id", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "google" + o.Separator + "client_secret"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.google.client_secret",
				Source: "--" + n,
			}
		}
		cfg.Auth.Google.ClientSecret = v
		set("auth.google.client_secret", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "github" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.github.enabled",
				Source: "--" + n,
			}
		}
		cfg.Auth.GitHub.Enabled = v
		set("auth.github.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "github" + o.Separator + "client_id"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.github.client_id",
				Source: "--" + n,
			}
		}
		cfg.Auth.GitHub.ClientID = v
		set("auth.github.client_id", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "github" + o.Separator + "client_secret"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.github.client_secret",
				Source: "--" + n,
			}
		}
		cfg.Auth.GitHub.ClientSecret = v
		set("auth.github.client_secret", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "custom" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.custom.enabled",
				Source: "--" + n,
			}
		}
		cfg.Auth.Custom.Enabled = v
		set("auth.custom.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "custom" + o.Separator + "client_id"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.custom.client_id",
				Source: "--" + n,
			}
		}
		cfg.Auth.Custom.ClientID = v
		set("auth.custom.client_id", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "custom" + o.Separator + "client_secret"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.custom.client_secret",
				Source: "--" + n,
			}
		}
		cfg.Auth.Custom.ClientSecret = v
		set("auth.custom.client_secret", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "custom" + o.Separator + "token_url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.custom.token_url",
				Source: "--" + n,
			}
		}
		cfg.Auth.Custom.TokenURL = v
		set("auth.custom.token_url", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "custom" + o.Separator + "user_url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.custom.user_url",
				Source: "--" + n,
			}
		}
		cfg.Auth.Custom.UserURL = v
		set("auth.custom.user_url", configulator.LayerCLI, "--"+n)
	}
	if n := "jwt" + o.Separator + "secret"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "jwt.secret",
				Source: "--" + n,
			}
		}
		cfg.JWT.Secret = v
		set("jwt.secret", configulator.LayerCLI, "--"+n)
	}
	if n := "mapbox" + o.Separator + "secret_token"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mapbox.secret_token",
				Source: "--" + n,
			}
		}
		cfg.Mapbox.SecretToken = v
		set("mapbox.secret_token", configulator.LayerCLI, "--"+n)
	}
	if n := "mapbox" + o.Separator + "public_token"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mapbox.public_token",
				Source: "--" + n,
			}
		}
		cfg.Mapbox.PublicToken = v
		set("mapbox.public_token", configulator.LayerCLI, "--"+n)
	}
	if n := "nats" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "nats.enabled",
				Source: "--" + n,
			}
		}
		cfg.NATS.Enabled = v
		set("nats.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "nats" + o.Separator + "url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "nats.url",
				Source: "--" + n,
			}
		}
		cfg.NATS.URL = v
		set("nats.url", configulator.LayerCLI, "--"+n)
	}
	if n := "nats" + o.Separator + "token"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "nats.token",
				Source: "--" + n,
			}
		}
		cfg.NATS.Token = v
		set("nats.token", configulator.LayerCLI, "--"+n)
	}
	if n := "parallel_log_parsers"; fs.Changed(n) {
		v, err := fs.GetUint(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "parallel_log_parsers",
				Source: "--" + n,
			}
		}
		cfg.ParallelLogParsers = v
		set("parallel_log_parsers", configulator.LayerCLI, "--"+n)
	}
	if n := "log_level"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log_level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log_level", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "http":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("http", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub hTTPShadow
				if err := sub.decodeJSON(dec, "http"); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "persistence":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("persistence", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub persistenceShadow
				if err := sub.decodeJSON(dec, "persistence"); err != nil {
					return err
				}
				s.Persistence = &sub
			}
		case "registration":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("registration", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub registrationShadow
				if err := sub.decodeJSON(dec, "registration"); err != nil {
					return err
				}
				s.Registration = &sub
			}
		case "auth":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("auth", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub authShadow
				if err := sub.decodeJSON(dec, "auth"); err != nil {
					return err
				}
				s.Auth = &sub
			}
		case "jwt":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("jwt", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub jWTShadow
				if err := sub.decodeJSON(dec, "jwt"); err != nil {
					return err
				}
				s.JWT = &sub
			}
		case "mapbox":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("mapbox", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub mapboxShadow
				if err := sub.decodeJSON(dec, "mapbox"); err != nil {
					return err
				}
				s.Mapbox = &sub
			}
		case "nats":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("nats", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub nATSShadow
				if err := sub.decodeJSON(dec, "nats"); err != nil {
					return err
				}
				s.NATS = &sub
			}
		case "parallel_log_parsers":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError("parallel_log_parsers", v, err)
				}
				if raw > math.MaxUint {
					return configJSONError("parallel_log_parsers", v, fmt.Errorf("%d overflows uint", raw))
				}
				num := uint(raw)
				s.ParallelLogParsers = &num
			default:
				return configJSONError("parallel_log_parsers", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "log_level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("log_level", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *hTTPShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "ipv4_host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.IPV4Host = &str
			default:
				return configJSONError(path+".ipv4_host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "ipv6_host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.IPV6Host = &str
			default:
				return configJSONError(path+".ipv6_host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw > math.MaxUint16 {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "tracing":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".tracing", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub tracingShadow
				if err := sub.decodeJSON(dec, path+".tracing"); err != nil {
					return err
				}
				s.Tracing = &sub
			}
		case "backend_url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.BackendURL = &str
			default:
				return configJSONError(path+".backend_url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "pprof":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".pprof", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub pProfShadow
				if err := sub.decodeJSON(dec, path+".pprof"); err != nil {
					return err
				}
				s.PProf = &sub
			}
		case "trusted_proxies":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".trusted_proxies", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".trusted_proxies"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TrustedProxies = &out
			}
		case "metrics":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".metrics", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub metricsShadow
				if err := sub.decodeJSON(dec, path+".metrics"); err != nil {
					return err
				}
				s.Metrics = &sub
			}
		case "cors_hosts":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".cors_hosts", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".cors_hosts"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.CORSHosts = &out
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *tracingShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "otlp_endpoint":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.OTLPEndpoint = &str
			default:
				return configJSONError(path+".otlp_endpoint", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *pProfShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *metricsShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "ipv4_host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.IPV4Host = &str
			default:
				return configJSONError(path+".ipv4_host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "ipv6_host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.IPV6Host = &str
			default:
				return configJSONError(path+".ipv6_host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw > math.MaxUint16 {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *persistenceShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "database":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".database", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub databaseShadow
				if err := sub.decodeJSON(dec, path+".database"); err != nil {
					return err
				}
				s.Database = &sub
			}
		case "uploads":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".uploads", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub uploadsShadow
				if err := sub.decodeJSON(dec, path+".uploads"); err != nil {
					return err
				}
				s.Uploads = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *databaseShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "driver":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Driver = &str
			default:
				return configJSONError(path+".driver", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "database":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Database = &str
			default:
				return configJSONError(path+".database", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "username":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Username = &str
			default:
				return configJSONError(path+".username", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "password":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.Password = &str
				default:
					return configJSONError(path+".password", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".password",
					Value: "(redacted)",
				}
			}
		case "host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Host = &str
			default:
				return configJSONError(path+".host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw > math.MaxUint16 {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "extra_parameters":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.ExtraParameters = &str
			default:
				return configJSONError(path+".extra_parameters", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *uploadsShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "driver":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Driver = &str
			default:
				return configJSONError(path+".driver", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "filesystem_options":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".filesystem_options", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub filesystemOptionsShadow
				if err := sub.decodeJSON(dec, path+".filesystem_options"); err != nil {
					return err
				}
				s.FilesystemOptions = &sub
			}
		case "s3_options":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".s3_options", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub s3OptionsShadow
				if err := sub.decodeJSON(dec, path+".s3_options"); err != nil {
					return err
				}
				s.S3Options = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *filesystemOptionsShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "directory":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Directory = &str
			default:
				return configJSONError(path+".directory", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *s3OptionsShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "region":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Region = &str
			default:
				return configJSONError(path+".region", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "bucket":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bucket = &str
			default:
				return configJSONError(path+".bucket", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "endpoint":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Endpoint = &str
			default:
				return configJSONError(path+".endpoint", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *registrationShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *authShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "google":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".google", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub googleShadow
				if err := sub.decodeJSON(dec, path+".google"); err != nil {
					return err
				}
				s.Google = &sub
			}
		case "github":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".github", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub gitHubShadow
				if err := sub.decodeJSON(dec, path+".github"); err != nil {
					return err
				}
				s.GitHub = &sub
			}
		case "custom":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".custom", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub customShadow
				if err := sub.decodeJSON(dec, path+".custom"); err != nil {
					return err
				}
				s.Custom = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *googleShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "client_id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.ClientID = &str
			default:
				return configJSONError(path+".client_id", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "client_secret":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.ClientSecret = &str
				default:
					return configJSONError(path+".client_secret", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".client_secret",
					Value: "(redacted)",
				}
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *gitHubShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "client_id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.ClientID = &str
			default:
				return configJSONError(path+".client_id", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "client_secret":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.ClientSecret = &str
				default:
					return configJSONError(path+".client_secret", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".client_secret",
					Value: "(redacted)",
				}
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *customShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "client_id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.ClientID = &str
			default:
				return configJSONError(path+".client_id", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "client_secret":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.ClientSecret = &str
				default:
					return configJSONError(path+".client_secret", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".client_secret",
					Value: "(redacted)",
				}
			}
		case "token_url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.TokenURL = &str
			default:
				return configJSONError(path+".token_url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "user_url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.UserURL = &str
			default:
				return configJSONError(path+".user_url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *jWTShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "secret":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.Secret = &str
				default:
					return configJSONError(path+".secret", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".secret",
					Value: "(redacted)",
				}
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *mapboxShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "secret_token":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.SecretToken = &str
				default:
					return configJSONError(path+".secret_token", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".secret_token",
					Value: "(redacted)",
				}
			}
		case "public_token":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.PublicToken = &str
			default:
				return configJSONError(path+".public_token", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *nATSShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.URL = &str
			default:
				return configJSONError(path+".url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "token":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.Token = &str
				default:
					return configJSONError(path+".token", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".token",
					Value: "(redacted)",
				}
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "http.ipv4_host = %v\n", c.HTTP.IPV4Host)
	fmt.Fprintf(&b, "http.ipv6_host = %v\n", c.HTTP.IPV6Host)
	fmt.Fprintf(&b, "http.port = %v\n", c.HTTP.Port)
	fmt.Fprintf(&b, "http.tracing.enabled = %v\n", c.HTTP.Tracing.Enabled)
	fmt.Fprintf(&b, "http.tracing.otlp_endpoint = %v\n", c.HTTP.Tracing.OTLPEndpoint)
	fmt.Fprintf(&b, "http.backend_url = %v\n", c.HTTP.BackendURL)
	fmt.Fprintf(&b, "http.pprof.enabled = %v\n", c.HTTP.PProf.Enabled)
	fmt.Fprintf(&b, "http.trusted_proxies = %v\n", c.HTTP.TrustedProxies)
	fmt.Fprintf(&b, "http.metrics.ipv4_host = %v\n", c.HTTP.Metrics.IPV4Host)
	fmt.Fprintf(&b, "http.metrics.ipv6_host = %v\n", c.HTTP.Metrics.IPV6Host)
	fmt.Fprintf(&b, "http.metrics.port = %v\n", c.HTTP.Metrics.Port)
	fmt.Fprintf(&b, "http.metrics.enabled = %v\n", c.HTTP.Metrics.Enabled)
	fmt.Fprintf(&b, "http.cors_hosts = %v\n", c.HTTP.CORSHosts)
	fmt.Fprintf(&b, "persistence.database.driver = %v\n", c.Persistence.Database.Driver)
	fmt.Fprintf(&b, "persistence.database.database = %v\n", c.Persistence.Database.Database)
	fmt.Fprintf(&b, "persistence.database.username = %v\n", c.Persistence.Database.Username)
	b.WriteString("persistence.database.password = (redacted)\n")
	fmt.Fprintf(&b, "persistence.database.host = %v\n", c.Persistence.Database.Host)
	fmt.Fprintf(&b, "persistence.database.port = %v\n", c.Persistence.Database.Port)
	fmt.Fprintf(&b, "persistence.database.extra_parameters = %v\n", c.Persistence.Database.ExtraParameters)
	fmt.Fprintf(&b, "persistence.uploads.driver = %v\n", c.Persistence.Uploads.Driver)
	fmt.Fprintf(&b, "persistence.uploads.filesystem_options.directory = %v\n", c.Persistence.Uploads.FilesystemOptions.Directory)
	fmt.Fprintf(&b, "persistence.uploads.s3_options.region = %v\n", c.Persistence.Uploads.S3Options.Region)
	fmt.Fprintf(&b, "persistence.uploads.s3_options.bucket = %v\n", c.Persistence.Uploads.S3Options.Bucket)
	fmt.Fprintf(&b, "persistence.uploads.s3_options.endpoint = %v\n", c.Persistence.Uploads.S3Options.Endpoint)
	fmt.Fprintf(&b, "registration.enabled = %v\n", c.Registration.Enabled)
	fmt.Fprintf(&b, "auth.google.enabled = %v\n", c.Auth.Google.Enabled)
	fmt.Fprintf(&b, "auth.google.client_id = %v\n", c.Auth.Google.ClientID)
	b.WriteString("auth.google.client_secret = (redacted)\n")
	fmt.Fprintf(&b, "auth.github.enabled = %v\n", c.Auth.GitHub.Enabled)
	fmt.Fprintf(&b, "auth.github.client_id = %v\n", c.Auth.GitHub.ClientID)
	b.WriteString("auth.github.client_secret = (redacted)\n")
	fmt.Fprintf(&b, "auth.custom.enabled = %v\n", c.Auth.Custom.Enabled)
	fmt.Fprintf(&b, "auth.custom.client_id = %v\n", c.Auth.Custom.ClientID)
	b.WriteString("auth.custom.client_secret = (redacted)\n")
	fmt.Fprintf(&b, "auth.custom.token_url = %v\n", c.Auth.Custom.TokenURL)
	fmt.Fprintf(&b, "auth.custom.user_url = %v\n", c.Auth.Custom.UserURL)
	b.WriteString("jwt.secret = (redacted)\n")
	b.WriteString("mapbox.secret_token = (redacted)\n")
	fmt.Fprintf(&b, "mapbox.public_token = %v\n", c.Mapbox.PublicToken)
	fmt.Fprintf(&b, "nats.enabled = %v\n", c.NATS.Enabled)
	fmt.Fprintf(&b, "nats.url = %v\n", c.NATS.URL)
	b.WriteString("nats.token = (redacted)\n")
	fmt.Fprintf(&b, "parallel_log_parsers = %v\n", c.ParallelLogParsers)
	fmt.Fprintf(&b, "log_level = %v\n", c.LogLevel)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
